### ISSUE TITLE
[Update Request] Upgrade FMDB to 2.7.x

### ISSUE THREAD

**Issue by benasher44** [optimizely/objective-c-sdk#144]
Hello! Currently FMDB in Optimizely (in one of the podspecs) is pinned to 2.6.2. We'd like to upgrade to FMDB 2.7.2 because it brings some really nice nullability annotations and other annotations that make FMDB more friendly for Swift users (and for Obj-C users wielding the clang static analyzer via the nullability annotations). Might you all be able to upgrade your version of FMDB, as wel as update your pinned version to be something like `~> 2.7.2` to allow for users of this pod easier upgrades in the future?

Thanks for your consideration!

**Comment by alda-optimizely** [comment]
@benasher44 Sure, we can bring that in in our next release. We are still working on some features, so may not release for another few weeks, fyi.

**Comment by benasher44** [comment]
No worries. I appreciate you all working it in!

**Comment by kellyroach-optimizely** [comment]
Issue #144 is essentially muted or resolved by release 1.4.0 which included the P.R. #170 
https://github.com/optimizely/objective-c-sdk/pull/170
https://github.com/optimizely/objective-c-sdk/commit/6cb3bd7be68547bc7ec63969e4147282d4f7920d
which snapshotted FMDB 2.7.2 to OPTLYFMDB .  Optimizely did do some modifications:
    Drop OPDBDatabasePool .
    Drop OPDBDatabaseAdditions .
    OPDBTests empty InfoPlist.strings --> outer space
    FMDBTests-Prefix.pch --> outer space
Optimizely made this change so that customers who wished to link in their own customized FMDB were able to do so without name collisions.  The CHANGELOG.md suggests to developers the following advice if they relied on FMDB being present:
"Supply your own FMDB or JSONModel or use OPTLYFMDB or OPTLYJSONModel if you previously counted on third party FMDB or JSONModel being present."
