### ISSUE TITLE
Carthage script failing on fmdb submodule

### ISSUE THREAD

**Issue by EdSancha** [optimizely/objective-c-sdk#217]
Doing a `carthage update $@ --use-ssh --use-submodules --no-build` fails with a message:

No submodule mapping found in .gitmodules for path 'OptimizelySDKUniversal/OptimizelySDKUniversal/Frameworks/fmdb'

Investigating I saw that this issue was fixed in v1.4.1 removing this submodules adding them as code, specifically on [this commit/PR](https://github.com/optimizely/objective-c-sdk/pull/170/commits/d87ec1b44ffac4098f458d4d55023bdd4630bf14) 

But it seems that fmdb and json where added back in the latest version 1.5.0 on [this PR](https://github.com/optimizely/objective-c-sdk/pull/212).  

As a test I tried building it pointing to v1.4.1 and it seemed to work fine (points to userProfileService-1.5.0-RC). Can you help us with this? Our team uses submodules intensively and our scripts need to use-submodules.

Thanks

**Comment by kellyroach-optimizely** [comment]
I've assigned an internal ticket OASIS-2370 to this issue.

**Comment by EdSancha** [comment]
Thank you Kelly, what's the ETA on this issue? We'd like to integrate the latest version and not an internal release candidate into our production code.

**Comment by kellyroach-optimizely** [comment]
The issue was a developer pushed a "1.5.0" tag onto a master branch
commit 12 days ago.  Carthage was seeing this commit as the "Latest release"
of Optimizely instead of the actual latest release 1.5.0 issued on
December 6, 2017 .  Since the master branch was also not perfect
(FMDB and JSONModel git submodules still in place), the "carthage update"
was not only getting the wrong commit, but breaking too.
I have removed the "1.5.0" tag that was pushed onto master branch
12 days ago.  I and a second Optimizely developer have both tested the
https://github.com/optimizely/objective-c-sdk README.md "Carthage" instructions
on a clean iOS CarthageTest sample app and confirmed that both
"carthage update" and the app building and running are working fine.

Can you check that our fix has resolved your issue #217?

**Comment by EdSancha** [comment]
Thanks! It's been resolved! 

I just wanted to ask, to make sure, if we need to explicitly add FMDB and JSONModel in the Cartfile. The documentation in the Optimizely portal says we need to but GitHub Readme doesn't. From the commits history, I think it's not needed. If that's the case changing the Documentation would be great! 

Thanks!

**Comment by kellyroach-optimizely** [comment]
The GitHub Readme is correct.
Since objective-c-sdk release 1.4.0 , it is only necessary to add one line to the Cartfile.
```
    github "optimizely/objective-c-sdk"
```
The README.md "Carthage" instructions describing the revised Cartfile containing
just one line is correct.  This change is also alluded to in our CHANGELOG.md description
of the 1.4.0 changes.  I've requested Optimizely's documentation team to update the
Optimizely portal's documentation.

**Comment by EdSancha** [comment]
Great! Thank you! 💯
